config/routes.rb
Rails.application.routes.draw do
  # Root
  get 'static/index'
  root 'gossips#index'

  # Static pages
  get 'team', to: 'static#team'
  get 'contact', to: 'static#contact'
  
  # Dynamic pages
  resources :gossips do
    resources :comments
    resources :tags
    resources :likes
  end
  resources :users, except: [:edit, :destroy]
  resources :cities, except: [:edit, :destroy]
  resources :sessions, only: [:index, :new, :create, :destroy]
  resources :profiles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  validates :comment, presence: true
  validates :user, presence: true
  validates :gossip, presence: true

end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tag_gossips
  has_many :tags, through: :tag_gossips
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { in: 3..14 }
  validates :content, presence: true

  def self.find(id)
    gossip = Gossip.find_by(id:id)
    return gossip 
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :gossip
end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  include BCrypt
  has_secure_password
  belongs_to :city, optional: true
  has_many :gossip
  has_many :likes
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  validates :password, presence: true, length: { minimum: 6 }

  # def initialize(attributes=nil)
  #   attr_with_defaults = {:first_name => "Non renseigné", :last_name => "Non renseigné", :age => 0, :city => City.create(name:"Non renseigné"), :description => "Non renseigné"}.merge(attributes)
  #   super(attr_with_defaults)
  # end

# CUSTOM METHODS =====================================

  def profile_url(first_name)
    url = "/welcome/#{first_name}"
    puts url
    return url
  end

  def self.find(id)
    user = User.find_by(id:id)
    return user 
  end


# BCRYPT METHODS =====================================
  # def password
  #   @password ||= Password.new(password_hash)
  # end

  # def password=(new_password)
  #   @password = Password.create(new_password)
  #   self.password_hash = @password
  # end

end

app/models/validations-template.rb
validates :name, length: { minimum: 2 }
  validates :bio, length: { maximum: 500 }
  validates :password, length: { in: 6..20 }
  validates :registration_number, length: { is: 6 }


validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

validates :email, uniqueness: true

validates :email, presence: true


# errors : 
def create_user
  user = User.new(params)
  if params[:first_name].empty?
    puts "Erreur, pas possible de créer un utilisateur sans prénom"
  elsif params[:email].unique?
    puts "Email déjà pris"
  elsif user.save?
    puts "Utilisateur bien créé !"
  end
end

# callbacks
class User < ActiveRecord
  after_create :send_welcome_email

  def send_welcome_email
    # le code qui envoit l'email
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:create, :update, :new, :edit, :destroy]

  def index
    @comments = Comment.all
  end

  def show

  end
  def create
    @gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.new(comment:params['comment']['comment'],user:current_user)

    if @comment.save
      flash[:success] = "Potin bien créé !"
      redirect_to @gossip
    else
      @comment.errors.full_messages
      redirect_to @gossip
    end
     
  end

  def destroy
    @gossip = Gossip.find(params[:gossip_id])

    @comment = Comment.find(params[:id])

    @comment.destroy

    redirect_to @gossip

  end

  private

  def comment_params
    params.require(:comment).permit(:comment)

  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    if session[:user_id]
      return true
    else
      return false
    end
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% @comments.each do |c| %>
  <div class="row mb-2">
        <div class="col-8 offset-2">
            <div class="card card-white post">
                <div class="post-heading">
                    <div class="float-left image">
                        <img src="http://bootdey.com/img/Content/user_1.jpg" class="img-circle avatar" alt="user profile image">
                    </div>
                    <div class="float-left meta">
                        <div class="title h5">
                            <b><%= link_to "#{c.user.first_name}", user_path(c.user.id) %></b>
                            comments.
                        </div>
                        <h6 class="text-muted time"><%=c.created_at%></h6>
                        <% if current_user == c.user %><span style="color:#dc3545 !important;"><b><%= link_to "Delete", gossip_comment_path(c.gossip_id, c.id), method: :delete %><%end%></b></span>
                    </div>
                </div> 
                <div class="post-description"> 
                    <p><%= c.comment %></p>

                </div>
            </div>
        </div>
        
    </div>
  

<%end%>


<div class="container">
    
</div>

app/views/comments/_form.html.erb
<%= form_for ([@gossip, @comment]), :class => 'form-group' do |f| %>

  <b><%= f.label :comment, 'Post a comment'  %></b>
  <%= f.text_area :comment, class:'form-control'  %>
<br/>
  <%= f.submit "Add a comment", class:'btn btn-primary' %>

<%end%>

app/views/comments/new.html.erb
test

app/views/comments/show.html.erb
test