config/routes.rb
Rails.application.routes.draw do
  # Root
  get 'static/index'
  root 'gossips#index'

  # Static pages
  get 'team', to: 'static#team'
  get 'contact', to: 'static#contact'
  
  # Dynamic pages
  resources :gossips do
    resources :comments
    resources :tags
    resources :likes
  end
  resources :users, except: [:edit, :destroy]
  resources :cities, except: [:edit, :destroy]
  resources :sessions, only: [:index, :new, :create, :destroy]
  resources :profiles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  validates :comment, presence: true
  validates :user, presence: true
  validates :gossip, presence: true

end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tag_gossips
  has_many :tags, through: :tag_gossips
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { in: 3..14 }
  validates :content, presence: true

  def self.find(id)
    gossip = Gossip.find_by(id:id)
    return gossip 
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :gossip
end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  include BCrypt
  has_secure_password
  belongs_to :city, optional: true
  has_many :gossip
  has_many :likes
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  validates :password, presence: true, length: { minimum: 6 }

  # def initialize(attributes=nil)
  #   attr_with_defaults = {:first_name => "Non renseigné", :last_name => "Non renseigné", :age => 0, :city => City.create(name:"Non renseigné"), :description => "Non renseigné"}.merge(attributes)
  #   super(attr_with_defaults)
  # end

# CUSTOM METHODS =====================================

  def profile_url(first_name)
    url = "/welcome/#{first_name}"
    puts url
    return url
  end

  def self.find(id)
    user = User.find_by(id:id)
    return user 
  end


# BCRYPT METHODS =====================================
  # def password
  #   @password ||= Password.new(password_hash)
  # end

  # def password=(new_password)
  #   @password = Password.create(new_password)
  #   self.password_hash = @password
  # end

end

app/models/validations-template.rb
validates :name, length: { minimum: 2 }
  validates :bio, length: { maximum: 500 }
  validates :password, length: { in: 6..20 }
  validates :registration_number, length: { is: 6 }


validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

validates :email, uniqueness: true

validates :email, presence: true


# errors : 
def create_user
  user = User.new(params)
  if params[:first_name].empty?
    puts "Erreur, pas possible de créer un utilisateur sans prénom"
  elsif params[:email].unique?
    puts "Email déjà pris"
  elsif user.save?
    puts "Utilisateur bien créé !"
  end
end

# callbacks
class User < ActiveRecord
  after_create :send_welcome_email

  def send_welcome_email
    # le code qui envoit l'email
  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :set_gossip, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:show, :index, :create, :update, :new, :edit, :destroy]
  before_action :is_author?, only: [:update, :edit, :destroy]

  def index
    @gossips = Gossip.all
  end

  def show
    @comment = Comment.new
    @comments = @gossip.comments
    set_id
    # @comments = Comment.where(gossip:@id)
    # print @comments
  end

  def new
    @gossip = Gossip.new
  end

  def edit
  end
  
  def update
    if @gossip.update(title:params['title'],content:params['content'],user:current_user)
      redirect_to @gossip
    else
      render :edit
    end
  end

  def create
    @gossip = Gossip.new(title:params['title'],content:params['content'],user:current_user)

    if @gossip.save
      flash[:success] = "Potin bien créé !"
      @success = "Bravo"
      redirect_to root_path(:add_gossip => @success)
    else
      @fail = @gossip.errors.full_messages
      render new_gossip_path
    end
  end

  def destroy
    @gossip.destroy
    redirect_to root_path(@gossip)
  end

  private

  def set_gossip
    @gossip = Gossip.find(params[:id])
  end
  
  def set_id
    @id = params['id']
  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

  def is_author?
    unless current_user == @gossip.user
      redirect_to @gossip
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    if session[:user_id]
      return true
    else
      return false
    end
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/edit.html.erb
<%= form_tag url_for(action: 'update'), method: "patch" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', "#{@gossip.title}" %>
      <br /> <br />

      <%= label_tag 'Content' %>
      <%= text_area_tag 'content', "#{@gossip.content}" %>
      <br /> <br />

      <%= submit_tag "Update Gossip" %>

    <% end %>

app/views/gossips/index.html.erb
<section class="team-section my-5">

  <!-- Section heading -->
  <h2 class="h1-responsive font-weight-bold my-5">Bienvenue sur The Gossip Project</h2>
  <!-- Section description -->
  <p class="grey-text w-responsive mx-auto mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    Fugit, error amet numquam iure provident voluptate esse quasi, veritatis totam voluptas nostrum quisquam
    eum porro a pariatur veniam.</p>


</section>
<% unless params[:add_gossip].nil? %>
<div class="alert alert-success" role="alert"><%=params[:add_gossip]%></div>
<% end %>
<% unless params[:add_user].nil? %>
<div class="alert alert-success" role="alert"><%=params[:add_user]%></div>
<% end %>

<div class="container">
<%if logged_in?%>
<div class="text-center mb-4"><%= link_to "Créer un Gossip", new_gossip_path, class:"btn btn-primary" %></div>
<%end%>
  <div class="row" style="margin:auto">
  <% @gossips.each_with_index do |g, index| %>

      <% i = index+1 %>

    <div class="card" style="width: 18rem;margin:10px">
      <div class="card-body" >
        <h5 class="card-title"><%= link_to "#{g.title}", gossip_path(g.id) %></h5>
        <p class="card-text"><%= "#{g.content}" %></p>
        <p style="font-style:italic">Posté à <%= g.created_at%> par <%= link_to "#{g.user.first_name}", user_path(g.user.id) %></p>
        <%= link_to "Voir le gossip", gossip_path(g.id), class:"btn btn-primary" %>
      </div>
    </div>


  <% end %>
</div>
</div>

app/views/gossips/new.html.erb
<br /><br /><% if @gossip.errors.any? %>
  <div class="alert alert-danger" role="alert"><p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul></div>
<% end %> <br />
<b>Hey, post un petit Gossip :)</b><br /><br />
<%= form_tag url_for(action: 'create'), method: "post", :class => 'form-group'  do %>

      <%= label_tag 'Gossip title' %>
      <%= text_field_tag 'title', nil, class:'form-control' %>
      <br /> 

      <%= label_tag 'Gossip content' %>
      <%= text_area_tag 'content', nil, class:'form-control' %>
      <br /> 
      <%= submit_tag "Create Gossip", class:"btn btn-primary" %>

    <% end %>

app/views/gossips/show.html.erb
<section class="team-section text-center my-5">

  <!-- Section heading -->
  <h2 class="h1-responsive font-weight-bold my-5"><%=@gossip.title%></h2>

    <p class="grey-text w-responsive mx-auto mb-5">Gossip n°<%=@id%></p>




<div style="border:1px solid grey;padding:20px;">
  <p>Titre du gossip : <strong><%=@gossip.title%></strong></p>
  <p>Contenu : <strong><i><%=@gossip.content%></i></strong></p>
  <p>Auteur : <strong><%= link_to "#{@gossip.user.first_name}", user_path(@gossip.user.id) %></strong></p>
  <p>Date de création : <strong><%=@gossip.created_at%></strong></p>
</div>
<%if current_user == @gossip.user%>
<%= link_to "Éditer le Gossip", edit_gossip_path, class:"btn btn-primary mb-3 mt-3" %>
<%= form_tag url_for(action: 'destroy'), method: "delete" do %>
      <%= submit_tag "Delete Gossip",class:"btn btn-danger mb-3" %>
<% end %>
<%end%>
  </section>
<% if @comment.errors.any? %>
  <div class="alert alert-danger" role="alert"><p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul></div>
<% end %>

<%= render 'comments/comment' %><br /><br />
<%= render 'comments/form' %>




<% if false %>

  ------------------------------------------------------------------------------------------------

  <%= form_tag :controller => 'comments', :action => 'create', method: "post" do %>

      <%= label_tag 'Author' %>
      <%= text_field_tag 'user', "Anonymous" %>
      <br /> <br />

      <%= label_tag 'Content' %>
      <%= text_area_tag 'comment_content' %>
      <br /> <br />

      <%= submit_tag "Post Comment" %>
    <% end %>

    =============================================================================================

    <div style="text-align:center;">
  <% @comments.each_with_index do |c, index| %>

    <% i = index+1 %>
    <p><%= c.content %></p>
    <p>Posté à <%= c.created_at %> par <%= link_to "#{c.user.first_name}", users_path(c.user.id) %></p>
    <%= link_to "Edit comment", gossip_path(c.id) %> | <%= link_to "Delete comment", gossip_path(c.id) %>
  <% end %>
  </div>



  <% end %>