config/routes.rb
Rails.application.routes.draw do
  # Root
  get 'static/index'
  root 'gossips#index'

  # Static pages
  get 'team', to: 'static#team'
  get 'contact', to: 'static#contact'
  
  # Dynamic pages
  resources :gossips do
    resources :comments
    resources :tags
    resources :likes
  end
  resources :users, except: [:edit, :destroy]
  resources :cities, except: [:edit, :destroy]
  resources :sessions, only: [:index, :new, :create, :destroy]
  resources :profiles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  validates :comment, presence: true
  validates :user, presence: true
  validates :gossip, presence: true

end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tag_gossips
  has_many :tags, through: :tag_gossips
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { in: 3..14 }
  validates :content, presence: true

  def self.find(id)
    gossip = Gossip.find_by(id:id)
    return gossip 
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :gossip
end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  include BCrypt
  has_secure_password
  belongs_to :city, optional: true
  has_many :gossip
  has_many :likes
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  validates :password, presence: true, length: { minimum: 6 }

  # def initialize(attributes=nil)
  #   attr_with_defaults = {:first_name => "Non renseigné", :last_name => "Non renseigné", :age => 0, :city => City.create(name:"Non renseigné"), :description => "Non renseigné"}.merge(attributes)
  #   super(attr_with_defaults)
  # end

# CUSTOM METHODS =====================================

  def profile_url(first_name)
    url = "/welcome/#{first_name}"
    puts url
    return url
  end

  def self.find(id)
    user = User.find_by(id:id)
    return user 
  end


# BCRYPT METHODS =====================================
  # def password
  #   @password ||= Password.new(password_hash)
  # end

  # def password=(new_password)
  #   @password = Password.create(new_password)
  #   self.password_hash = @password
  # end

end

app/models/validations-template.rb
validates :name, length: { minimum: 2 }
  validates :bio, length: { maximum: 500 }
  validates :password, length: { in: 6..20 }
  validates :registration_number, length: { is: 6 }


validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

validates :email, uniqueness: true

validates :email, presence: true


# errors : 
def create_user
  user = User.new(params)
  if params[:first_name].empty?
    puts "Erreur, pas possible de créer un utilisateur sans prénom"
  elsif params[:email].unique?
    puts "Email déjà pris"
  elsif user.save?
    puts "Utilisateur bien créé !"
  end
end

# callbacks
class User < ActiveRecord
  after_create :send_welcome_email

  def send_welcome_email
    # le code qui envoit l'email
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params['id'])
  end

  def index
    @all_users = User.all
  end

  def new
    @user = User.new
  end

  def create
    # if city exist?
    if City.find_by(name:params['city']) != nil
      city = City.find_by(name:params['city'].humanize)
    else
      city = City.create(name:params['city'].humanize)
    end
    
    # new user
    @user = User.new(email:params['email'].downcase, password:params['password'], city: city, age:params['age'], first_name:params['first_name'].humanize, last_name: params['last_name'].humanize)

    if params['password'] == params['password_confirmation']
      if @user.save
        @success_login = "Bravo ! User inscrit !"
        log_in(@user)
        redirect_to root_path(:add_user => @success_login)
      else
        @user.errors.full_messages
        render 'new'
      end
    else
      @pwd_not_match = "Les passwords ne matchent pas !"
      render 'new'
    end
    # save or error
    

  end

  def edit

  end

  def update 

  end

  def destroy

  end


  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    if session[:user_id]
      return true
    else
      return false
    end
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user/authors_list.html.erb
<section class="team-section my-5">

  <!-- Section heading -->
  <h2 class="h1-responsive font-weight-bold my-5">Tous les auteurs</h2>
  <!-- Section description -->
  <p class="grey-text w-responsive mx-auto mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    Fugit, error amet numquam iure provident voluptate esse quasi, veritatis totam voluptas nostrum quisquam
    eum porro a pariatur veniam.</p>


</section>


<div class="container">
  <div class="row">
  <% @all_users.each_with_index do |a, index| %>

      <% i = index+1 %>

    <div class="card" style="width: 18rem;margin:10px">
      <div class="card-body" >
        <h5 class="card-title"><strong><%= link_to "#{a.first_name} #{a.last_name}", user_path(i) %></strong></h5>
        <p class="card-text"><%= "#{a.age}" %> ans.<br /><i><%= "#{a.email}" %></i><br />Lieu : <strong><%= "#{a.city.name}" %></strong></p>
        </p>
        <%= link_to "Voir l'auteur", user_path(i), class:"btn btn-primary" %>
      </div>
    </div>


  <% end %>
</div>
</div>

app/views/user/show_user.html.erb
<section class="team-section text-center my-5">

  <!-- Section heading -->
  <h2 class="h1-responsive font-weight-bold my-5"><%= @user.first_name %> <%= @user.last_name %></h2>

<div style="border:1px solid grey;padding:20px;">
  <p>Prénom : <strong><%= link_to "#{@user.first_name}", user_path(@user.id) %></strong></p>
  <p>Nom : <strong><%= @user.last_name %></strong></p>
  <p>Age : <strong><%= @user.age %></strong></p>
  <p>Ville : <strong><% city = @user.city %><%=city.name%></strong></p>
  <p>Description : <strong><i><%= @user.description %></i></strong></p>
</div>
  </section>

app/views/users/_register.html.erb
<%= form_for ([@gossip, @comment]) do |f| %>

  <%= f.label :comment %>
  <%= f.text_field :comment %>

  <%= f.submit "Add a comment" %>

<%end%>

app/views/users/index.html.erb
<section class="team-section my-5">

  <!-- Section heading -->
  <h2 class="h1-responsive font-weight-bold my-5">Tous les auteurs</h2>
  <!-- Section description -->
  <p class="grey-text w-responsive mx-auto mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    Fugit, error amet numquam iure provident voluptate esse quasi, veritatis totam voluptas nostrum quisquam
    eum porro a pariatur veniam.</p>


</section>


<div class="container">
  <div class="row">

  <% @all_users.each_with_index do |a, index| %>

    <% i = index+1 %>

    <div class="card" style="width: 18rem;margin:10px">
      
      <div class="card-body" >
        
        <h5 class="card-title"><strong><%= link_to "#{a.first_name} #{a.last_name}", user_path(i) %></strong></h5>
        
        <p class="card-text"><%= "#{a.age}" %> ans.<br /><i><%= "#{a.email}" %></i><br />Lieu : <strong>
        
        <%= a.city.name if !a.city.nil?%>
        <%= "Non renseigné" if a.city.nil?%>
        </strong></p>
        </p>
        <%= link_to "Voir l'auteur", user_path(i), class:"btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/users/new.html.erb
<br /><br /><% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert"><p>Nous n'avons pas réussi à créer le user pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul></div>
<% end %> 

<% unless @pwd_not_match.nil? %>
<div class="alert alert-danger" role="alert"><%= @pwd_not_match %></div>
<% end %>


<br />

<%if !logged_in?%>
<%= form_tag url_for(action: 'create'), method: "post", :class => 'form-group' do %>
      Hello ! <br />Inscris-toi pour profiter du site :)<br/><br/>

      <%= label_tag 'Email' %><br/>
      <%= text_field_tag 'email', nil, class:'form-control' %>
      <br /> 

      <%= label_tag 'Password' %><br/>
      <%= password_field_tag 'password', nil, class:'form-control' %>
      <br /> 

      <%= label_tag 'Re-Password' %><br/>
      <%= password_field_tag 'password_confirmation', nil, class:'form-control' %>
      <br /> 

      <%= label_tag 'City' %><br/>
      <%= text_field_tag 'city', nil, class:'form-control' %>
      <br /> 

      <%= label_tag 'Age' %><br/>
      <%= text_field_tag 'age', nil, class:'form-control' %>
      <br /> 

      <%= label_tag 'First name' %><br/>
      <%= text_field_tag 'first_name', nil, class:'form-control' %>
      <br /> 

      <%= label_tag 'Last Name' %><br/>
      <%= text_field_tag 'last_name', nil, class:'form-control' %>
      <br />
      <%= submit_tag "S'enregistrer", class:'btn btn-primary' %>

    <% end %>
    <%end%>

app/views/users/show.html.erb
<section class="team-section text-center my-5">

  <!-- Section heading -->
  <h2 class="h1-responsive font-weight-bold my-5"><%= @user.first_name %> <%= @user.last_name %></h2>

<div style="border:1px solid grey;padding:20px;">
  <p>Prénom : <strong><%= link_to "#{@user.first_name}", user_path(@user.id) %></strong></p>
  <p>Nom : <strong><%= @user.last_name %></strong></p>
  <p>Age : <strong><%= @user.age %></strong></p>
  <p>Ville : <strong><%= link_to "#{@user.city.name}", city_path(@user.city.id) %></strong></p>
  <p>Description : <strong><i><%= @user.description %></i></strong></p>
</div>

  </section>

app/views/users/welcome.html.erb
<section class="team-section text-center my-5">

  <!-- Section heading -->
  <h2 class="h1-responsive font-weight-bold my-5">Bonjour <%= @user_welcome %></h2>
  <!-- Section description -->
  <p class="grey-text w-responsive mx-auto mb-5">On ne sait pas vraiment ce que tu fais ici... mais bienvenue quand même !</p>

  </section>